### ISSUE TITLE
Order of Operations: Exponentiation and Parens

### ISSUE THREAD

**Issue by keenanlang** [epics-modules/calc#10]
**Describe the issue**

The calc module breaks when dealing with negations, parentheses, and exponentiation.

**Steps to reproduce**
1. Type -(-2)**2 into the CALC field of a calcout record.
2. Process the record

**Expected behaviour**

VAL should be -4, this can be confirmed by typing the same equation into a python session or into a calculator program.

**Actual behaviour**

VAL is 4

**Build Environment**
Architecture: linux-x86_64
Epics Base Version: 3.15.5
Dependent Module Versions: sscan: master, seq: 2-2-2

**Comment by keenanlang** [comment]
Issue was found when testing acalcout, but issue is actually in Base.

**Comment by anjohnson** [comment]
The precedence of calc's power operators `**` and `^` is documented in the [AppDevGuide](http://www.aps.anl.gov/epics/base/R3-14/12-docs/AppDevGuide/node20.html#SECTION002021000000000000000) under `19.2.1.5 Arithmetic Operators`

There are several things I'd like to change in the calc engine, but I don't want to break existing expressions.
