### ISSUE TITLE
Test applications do not build with Visual Studio

### ISSUE THREAD

**Issue by MarkRivers** [epics-modules/calc#12]
Keenan added tests/acalcTest.cpp and scalcTest.cpp.  However, these do not build on Windows with Visual Studio 2010 or 2015.  Problems:

- "and" and "not" are being used instead of && and !
- pow, atan2, and sqrt are being used ambiguously, which is an error on Visual Studio

Another problem is that when I run acalcTest.exe it says it completed all the tests OK, but then pops up a Windows dialog box saying the application has crashed.

I have fixed the compile problems and and am making a pull request.  I have not fixed the crash error.

Problems like this are why all synApps modules should be in the Jenkins build server, which can automatically build for Windows, Linux, vxWorks, and Darwin.

**Comment by anjohnson** [comment]
Presumably this particular issue can be closed; PR #13 that fixed it was merged back in August 2017.

Any chance of getting a tagged release of calc now that it builds properly against Base-7.0.x?

- Andrew
