### ISSUE TITLE
Does swait record work with EPICS 7?

### ISSUE THREAD

**Issue by prjemian** [epics-modules/calc#19]
Does the *swait* record work with EPICS 7?  An [issue with the 2slit database](https://github.com/epics-modules/optics/issues/7) makes me question this?

It's not just the *2slit* database, but that [user calcs](https://github.com/epics-modules/calc/blob/3.16/calcApp/Db/userCalcN.db#L16-L21) use the *swait* record.

**Comment by MarkRivers** [comment]
I am using the 2slit.db with EPICS 7 at sector 13 with no apparent problems.

![image](https://user-images.githubusercontent.com/6115534/63191845-2fd51380-c02f-11e9-8002-787e8e729d34.png)

These are the swait records in one of my IOCs:
```
ioc13bma> dbl "swait"
13BMA:Slit1VRWait
13BMA:Slit1VLWait
13BMA:Slit1HRWait
13BMA:Slit1HLWait
13BMA:Slit2VRWait
13BMA:Slit2VLWait
13BMA:Slit3VRWait
13BMA:Slit3VLWait
13BMA:Slit4HRWait
13BMA:Slit4HLWait
13BMA:userCalc1
13BMA:userCalc2
13BMA:userCalc3
13BMA:userCalc4
13BMA:userCalc5
13BMA:userCalc6
13BMA:userCalc7
13BMA:userCalc8
13BMA:userCalc9
13BMA:userCalc10
```

**Comment by prjemian** [comment]
I'll take this as a positive.  Means I need to investigate further if I encounter this again.  Time to recompile with new versions anyway.  Thanks for the info.
