### ISSUE TITLE
editSseq is started by default in sseq.iocsh

### ISSUE THREAD

**Issue by kmpeters** [epics-modules/calc#21]
The editSseq sequence program is started by default in sseq.iocsh:
https://github.com/epics-modules/calc/blob/5ea66fb8c2e680971104a679cc7b1d9532f61d92/iocsh/sseq.iocsh#L14
But the sequencer is not included by default in the RELEASE file:
https://github.com/epics-modules/calc/blob/5ea66fb8c2e680971104a679cc7b1d9532f61d92/configure/RELEASE#L16
An IOC based on xxx, compiled against a calc module with the default configuration, will see this error if ``common.iocsh`` is loaded:
```
seq &editSseq, 'P=xxx:,Q=ES:'
Can't find sequencer `editSseq'.
```
There are two obvious solutions:
1. Comment out the editSseq support in sseq.iocsh
2. Move the editSseq support to its own .iocsh file, which could then be commented out by default in xxx's common.iocsh

**Comment by Engbretson** [comment]
Why isn’t one of the obvious solutions to *not* comment it out?

 

After all, the default is to use Scan in order to build the swait record.

 

I have seen this message on every recent ioc that I have deployed . . . . but no one, including myself, had any clue to what editSseq actually does.

**Comment by kmpeters** [comment]
> Why isn’t one of the obvious solutions to *not* comment it out?

I assume you mean not comment out ``SNCSEQ`` from ``calc/configure/RELEASE``.  The reason this hasn't been done in the past is that it would require every module and IOC that includes ``calc`` to also include the sequencer, which is a fairly steep cost for the inclusion of some helpful sequence programs.

My understanding of editSseq is that it lets one rearrange the entries in the sseq record without having to manually delete and enter lots of text.

**Comment by Engbretson** [comment]
*BUT* if seq is already being included, at least in building a typical XXX deployment of something to vxWorks, isn’t that overhead already in there somewhere? 

 

Question: if having this state notation file compiled as part of CALC causes dependencies that you don’t want, shouldn’t that file then be moved to somewhere else and it itself depend upon CALC to  decide whether to do it or not? Where else do these sorts of files get generated? Do they have similar issues?

 

I.e. the XXX makefile contains code that checks to see if various synApps modules are defined and adds in the dbd files and have link lib references put in the build as well. Can CALC not be slightly smarter and be aware of if this overhead is going to be in there anyway, and then either build it or not build it?

**Comment by anjohnson** [comment]
EPICS support modules can generate and install files named `CONFIG_*` into their `$(TOP)/cfg` directory (use `CFG += CONFIG_filename` to install them) which set variables that all downstream module Makefiles will include automatically. This is a very powerful technique that can reduce the need for conditionals in the downstream modules, and is available with Base versions back to 3.14.10. For example if the sequencer provided a file in its `cfg/` directory that contained:

```Makefile
EPICS_SNCSEQ_LIBS = pv seq
```
then calcApp/src/Makefile could unconditionally say something like
```Makefile
calc_LIBS += $(EPICS_SNCSEQ_LIBS)
```
and those libraries would be linked if the SNCSEQ is set in the calc/RELEASE file and not if it isn't (because the variable expands to nothing if it isn't set). You might consider if/how you could use this feature to solve this kind of issue.

Oh yes, and Base has long defined the variable `CAT` which is set to either `cat` or `$(PERL) -MExtUtils::Command -e cat` as needed (could be used at the end of calcApp/src/Makefile).

**Comment by kmpeters** [comment]
@Engbretson,

> Can CALC not be slightly smarter and be aware of if this overhead is going to be in there anyway, and then either build it or not build it?

The ``calc/calcApp/src/Makfile`` is already aware that editSseq should only be included if ``SNCSEQ`` is defined:
https://github.com/epics-modules/calc/blob/5ea66fb8c2e680971104a679cc7b1d9532f61d92/calcApp/src/Makefile#L88-L94
https://github.com/epics-modules/calc/blob/5ea66fb8c2e680971104a679cc7b1d9532f61d92/calcApp/src/calcSupport_withSNCSEQ.dbd#L2

The new approach that Andrew outlined above could make it much easier for all the modules that include modules that may have included sequence programs, but none of that has any effect on the default configuration of an iocsh file, which is intended to be sourced without modification.

**Comment by anjohnson** [comment]
You could of course generate and install the `.iocsh` files at build time. The generator could then take account of whether other modules are enabled or not. IMHO the `$(TOP)/iocsh` directory should be an install directory, not a source directory...

**Comment by keenanlang** [comment]
Where do we think the ioc shell file source directory should be? ***App/iocsh or somewhere in iocBoot?

**Comment by anjohnson** [comment]
Not under `iocBoot` please, there are no files installed from that area and I personally don't think of it as a source area. You can have multiple source directories named `*App/*[Ss]rc` if you want to keep them separate, or you can just install the `.iocsh` files from an existing src directory.

There is a convention (which recent template <top>/Makefiles support, so update if you adopt it) to separate the building of support libraries and databases from the building of IOC applications. Sources under `*Sup` build support libraries (records, devices etc.) whereas sources under `*App` build IOCs using those libraries. The Makefile ensures that all Sup directories are built before any App directories, so you don't have to manually set dependency rules for them, although if you have multiple Sup directories with dependencies between them you would need to set the later `*Sup_DEPEND_DIRS` variables in the top-level Makefile to enforce their build ordering.

We don't have code or templates in `makeBaseApp.pl` to create Sup directories yet. You have to create them by hand or rename an App directory, but other than the name they are identical.

**Comment by keenanlang** [comment]
With 3ca0b78 and the current master version of synApps/configure, calc installs its ioc shell scripts and doesn't install sseq.iocsh if the support isn't included.

Though the cause of the original issue is that the assemble_synApps script should have been uncommenting the SNCSEQ definition in CALC. This is an issue of assumptions that XXX is making, not really anything wrong per se with the Calc module.
