### ISSUE TITLE
widget overlap in userCalc.ui screen for caQtDM

### ISSUE THREAD

**Issue by prjemian** [epics-modules/calc#22]
Suspect there are widget overlaps in the .ald (MEDM) file.  Here's the comparison:
![userCalc screens](https://user-images.githubusercontent.com/2279984/76342973-acc22600-62bc-11ea-8087-01e1f265c40d.jpg)

The *YES* dropdown menu overlaps the input PV name entry box.  Look at the bounding box in the MEDM file.

Also check for same problem in other calc-related screens.

**Comment by prjemian** [comment]
Checked `userCalc.adl` for size of widgets with `INAP`, `INBP`, `INCP`, & `INDP`.  All have the same width (50).

**Comment by prjemian** [comment]
Same for `userCalc.ui`.  All have same width (50).  Next look at start position of `INAN` (et al.) entry fields.

**Comment by prjemian** [comment]
In `userCalc.ui`, the `INnN` fields all have `x=65`, same as `userCalc.adl`.

So, why are they displayed differently?  Even within the `userCalc.ui` screen, `INBP` is different from the other three.  Why is that?

**Comment by timmmooney** [comment]
Hi Pete,

That's not what I see when I bring up a userCalc.

Tim Mooney (mooney@anl.gov) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________

**Comment by anjohnson** [comment]
Z-order and widget overlap maybe? Do all the converters retain the same back-to-front ordering as the original source?

**Comment by MarkRivers** [comment]
>That's not what I see when I bring up a userCalc.

Me either.  This is what I see with a userCalc.ui that I just converted from the adl file.  It is identical to the file on the master branch in calc.

![image](https://user-images.githubusercontent.com/6115534/76655242-dee0bb80-653a-11ea-963b-465126474ec1.png)

**Comment by prjemian** [comment]
Next, I'll test with the caQtDM on /APSshare.  Something odd here.  And compare versions.

**Comment by MarkRivers** [comment]
The above screen shot was done running caQtDM 4.1.7.

**Comment by prjemian** [comment]
I have been using v4.2.5_Development from the GitHub master branch.

**Comment by prjemian** [comment]
Recently upgraded from 4.2.4

**Comment by prjemian** [comment]
@anjohnson Not sure that it is widget order.  We've checked the widget geometries and they should not be overlapping.  Looks like the rendering is off.  I have checked the .adl and .ui files from the calc master branch.  The geometry text in the file agrees but the rendering of the .ui is off.

**Comment by MarkRivers** [comment]
I just tested with the version in APSshare/caqtdm/bin/caQtDM.  That is version 3.8.10, so much older than either 4.1.7 (me) or 4.2.5_Development (you).  It looks different, but does not have the widget layout problem you see:
![image](https://user-images.githubusercontent.com/6115534/76684263-6f210e00-65d8-11ea-94da-ca9a5ff03640.png)

I then tested with version 4.2.0 (/APSshare/caqtdm/caqtdm-4.2.0/caQtDM_Binaries/caQtDM).  That appears to be the most recent version on APSshare.  The display looks very similar to what I see with 4.1.7 and again has no issues:
![image](https://user-images.githubusercontent.com/6115534/76684293-b7403080-65d8-11ea-9fdc-e33b64ca1167.png)

**Comment by prjemian** [comment]
I confirm that the `userCalc.ui` file is rendered differently by a previous version of caQtDM.  The version available from `/APSshare/bin/caQtDM` is 2.4.0, built in May 2018.

```
cd /tmp
git clone https://github.com/epics-modules/calc
cd calc/calcApp/op/
medm -x -macro "P=sky:,C=userCalc1" adl/userCalc.adl  &
caQtDM -macro "P=sky:,C=userCalc1" ui/autoconvert/userCalc.ui &
```

Here's what I see today:

![Clipboard01](https://user-images.githubusercontent.com/2279984/76691423-9f889c80-6618-11ea-8955-c5a568f0f220.jpg)

**Comment by prjemian** [comment]
I should move this issue to the [caQtDM repo](https://github.com/caqtdm/caqtdm).

**Comment by prjemian** [comment]
GH won't transfer this issue that far.  Closing here, opening there.

**Comment by prjemian** [comment]
Thanks for all the help testing.
