### ISSUE TITLE
Upgrade calc module to EPICS 3.16

### ISSUE THREAD

**Issue by hdante** [epics-modules/calc#3]
#2

**Comment by prjemian** [comment]
Doesn't this issue duplicate #2?  We can do all the discussion there.

**Comment by hdante** [comment]
This was a failed attempt to assign the milestone. I believe I don't have the permission for doing assignments.

**Comment by prjemian** [comment]
Figured that might be the case, so assigned the milestone myself.  Closing this issue now.
